language: php
php:
  - '7.0'
  - hhvm # on Trusty only
# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction
# Commands you want to run that will verify your build.
script: phpunit
